site_title: "碎碎的知识库"
site_logo: "/global_static/logo.png"
footer_text: "欢迎来到小站"
footer_copyright: ""
icp:
  number: "粤ICP备16050855号"
  link: "https://beian.miit.gov.cn/"
home_notice_text: "当前站点正在改版。请见谅！"
books_page_path: "/books/"
books_page_title: "全部书籍"
home_card_layout:
  column_count: 3
  show_book_desc: true
  show_version_tag: true
global_nav:
  - name: "门户首页"
    link: "/"
  - name: "全部书籍"
    link: "/books/index.html"
custom_global_css: ""
enable_sitemap: true
enable_rss: true
