site_title: "蛋蛋的知识库"
site_logo: "/global_static/logo.png"
footer_text: "谢谢光顾 ~ "
footer_copyright: ""
icp:
  number: "京ICP备2026001234号-1"
  link: "https://beian.miit.gov.cn/"
home_notice_text: "欢迎光临"
books_page_path: "/books/"
books_page_title: "书单"
home_card_layout:
  column_count: 3
  show_book_desc: true
  show_version_tag: true
global_nav:
  - name: "首页"
    link: "/"
  - name: "书单"
    link: "/books/index.html"
custom_global_css: ""
enable_sitemap: true
enable_rss: true
